/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIview;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nopal Nich
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        Connect();
        this.setLocationRelativeTo(null);

    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/tambak", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_tanggallahir = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_ulangpassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_alamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField_namadepan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_namabelakang = new javax.swing.JTextField();
        jLabel_loginakun = new javax.swing.JLabel();
        jButton_create = new javax.swing.JButton();
        jButton_cancelr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/button -.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/button x.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal Lahir :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        jTextField_tanggallahir.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_tanggallahir.setText("YYYY-MM-DD");
        jTextField_tanggallahir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_tanggallahirMouseClicked(evt);
            }
        });
        jTextField_tanggallahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tanggallahirActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_tanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 230, 40));

        jPasswordField_password.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_password.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 210, 40));

        jTextField_username.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 210, 30));

        jPasswordField_ulangpassword.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_ulangpassword.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField_ulangpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_ulangpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_ulangpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 210, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ulangi Password :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Alamat :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea_alamat.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_alamat.setColumns(20);
        jTextArea_alamat.setRows(5);
        jScrollPane1.setViewportView(jTextArea_alamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Depan :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jTextField_namadepan.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_namadepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_namadepanActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_namadepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 210, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Belakang :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jTextField_namabelakang.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_namabelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_namabelakangActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_namabelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 210, 30));

        jLabel_loginakun.setBackground(new java.awt.Color(255, 180, 0));
        jLabel_loginakun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_loginakun.setForeground(new java.awt.Color(0, 51, 153));
        jLabel_loginakun.setText("Sudah Punya Akun?, Login Skuy");
        jLabel_loginakun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_loginakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_loginakunMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_loginakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 790, -1, -1));

        jButton_create.setBackground(new java.awt.Color(255, 255, 255));
        jButton_create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_create.setForeground(new java.awt.Color(0, 0, 0));
        jButton_create.setText("Create");
        jButton_create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 740, 130, -1));

        jButton_cancelr.setBackground(new java.awt.Color(153, 0, 0));
        jButton_cancelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_cancelr.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancelr.setText("Cancel\n");
        jButton_cancelr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cancelr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelrActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cancelr, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 740, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIpack/FormRegist.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        JFrame frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame, "Apakah Kamu Mau Keluar Aplikasi? ", "EXIT",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked
    }
    private void jTextField_tanggallahirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_tanggallahirMouseClicked
        jTextField_tanggallahir.setText(null);
    }//GEN-LAST:event_jTextField_tanggallahirMouseClicked

    private void jTextField_tanggallahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tanggallahirActionPerformed

        jTextField_tanggallahir.setText("");
    }//GEN-LAST:event_jTextField_tanggallahirActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed

    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jPasswordField_ulangpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_ulangpasswordActionPerformed
        jPasswordField_ulangpassword.setText("");
    }//GEN-LAST:event_jPasswordField_ulangpasswordActionPerformed

    private void jTextField_namadepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_namadepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_namadepanActionPerformed

    private void jTextField_namabelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_namabelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_namabelakangActionPerformed

    private void jLabel_loginakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginakunMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_loginakunMouseClicked

    private void jButton_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createActionPerformed

        try {
            String txtnamadepan = jTextField_namadepan.getText();
            String txtnamabelakang = jTextField_namabelakang.getText();
            String txtusername = jTextField_username.getText();
            String txtpassword = String.valueOf(jPasswordField_password.getPassword());
            String txtulangpassword = String.valueOf(jPasswordField_ulangpassword.getPassword());
            String txttanggallahir = jTextField_tanggallahir.getText();
            String txtalamat = jTextArea_alamat.getText();

            pst = con.prepareStatement("INSERT INTO user (nama_depan, nama_belakang, username, password, tanggal_lahir, alamat) values (?,?,?,?,?,?)");
            pst.setString(1, txtnamadepan);
            pst.setString(2, txtnamabelakang);
            pst.setString(3, txtusername);
            pst.setString(4, txtpassword);
            pst.setString(5, txttanggallahir);
            pst.setString(6, txtalamat);

            int k = pst.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(this, "User Berhasil Ditambahkan!");

            } else {

                JOptionPane.showMessageDialog(this, "User Gagal Ditambahkan");
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_createActionPerformed

    private void jButton_cancelrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelrActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jButton_cancelrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancelr;
    private javax.swing.JButton jButton_create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_loginakun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JPasswordField jPasswordField_ulangpassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_alamat;
    private javax.swing.JTextField jTextField_namabelakang;
    private javax.swing.JTextField jTextField_namadepan;
    private javax.swing.JTextField jTextField_tanggallahir;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
